
services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: BankRest
      POSTGRES_PASSWORD: BankRest
      POSTGRES_DB: BankRest
    ports:
      - "5432:5432"
    networks:
      - bank-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres_user" ]
      interval: 30s
      timeout: 10s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5433:5433"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - bank-network
    depends_on:
      - postgres

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bank-rest:latest
    container_name: bank-rest-app
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8060:8060"
    environment:
      CARD_SECRET: bf7c68b9cade5c7dd4524e955cb15710fe51c76754d0c8d5933a6747d5ed77147da465b61d33ea11fa6f8983e4b8d81c2c8fc7ca72c4ea1dfca4835a6ad2f25d
      JWT_SECRET: TXlTdXBlcktleUNhcmRGb3JCYW5rc2xz
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/BankRest
      SPRING_DATASOURCE_USERNAME: BankRest
      SPRING_DATASOURCE_PASSWORD: BankRest
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_JPA_SHOW_SQL: "true"
    networks:
      - bank-network

volumes:
  postgres_data: {}
  pgadmin_data: {}
  postgres: {}

networks:
  bank-network:
    driver: bridge
