#
# application.yml — главный конфигурационный файл Spring Boot.

#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.

spring:
  application:
    name: BankRest
  datasource:
    url: jdbc:postgresql://localhost:5432/BankRest
    username: BankRest
    password: BankRest
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:docs/
      static-path-pattern: /docs/**

server:
  port: 8060

auth:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 3600000

springdoc:
  swagger-ui:
    url: /v3/api-docs.yaml


